#!/bin/sh

commit_msg=$(cat "$1")

if echo "$commit_msg" | grep -Eq "^Merge "; then
  exit 0
fi

if ! echo "$commit_msg" | grep -Eq "^\[[a-zA-Z0-9]+\]: .+"; then
  echo "❌ Commit message must follow format:"
  echo "[86b9kxbb1]: your message here"
  exit 1
fi